#Makefile
all: echo chargen daytime time discard all_in_one

echo:
	cd echo && $(MAKE)

chargen:
	cd chargen && $(MAKE)

daytime:
	cd daytime && $(MAKE)

time:
	cd time && $(MAKE)

discard:
	cd discard && $(MAKE)

all_in_one:
	cd all_in_one && $(MAKE)

.PHONY: all echo chargen daytime time discard all_in_one
