#Makefile
all: simple asio twisted netty idleconnection maxconnection roundtrip

simple:
	cd simple && $(MAKE)

asio:
	cd asio && $(MAKE)

twisted:
	cd twisted && $(MAKE)

netty:
	cd netty && $(MAKE)

idleconnection:
	cd idleconnection && $(MAKE)

maxconnection:
	cd maxconnection && $(MAKE)

roundtrip:
	cd roundtrip && $(MAKE)

.PHONY: all simple asio twisted netty idleconnection maxconnection roundtrip
